### PR TITLE
Editorial changes and removed dead code

### PR DESCRIPTION
**Pull request by kiritigowda**

### CODE REVIEW

**Comment by kiritigowda** [comment]
Global Attribute 56 - CPU Initialize added.

**Comment by rgiduthuri** [comment]
>    LIVE_STITCH_ATTR_USE_CPU_FOR_INIT         =   56,   // use gpu kernels for initialize stitch: 0:OFF 1:ON (default:1)

@kiritigowda comment and default value needs change too...

**Comment by rgiduthuri** [comment]
> 		g_live_stitch_attr[LIVE_STITCH_ATTR_STITCH_MODE] = (float)stitching_mode_normal;

Also noticed other changes not related to the subject -- could be accidental.
It's hard to see them because of whitespace changes. It will be great if the whitespaces are kept as-is until I get a change to whitespace in the project overall.

**Comment by kiritigowda** [comment]
merge #53 is Global Attribute 56 changes. merge #52 could be visited after we merge 53 to accept the editorial changes.

**Pull request closed without merging**
